version: "3"

services:
  phoenix:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    restart: always
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7.26
    volumes:
      - .docker/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - mynetwork
 
networks:
  mynetwork:
    driver: bridge